[package]
name = "bcrypt"
version = "0.6.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
license = "MIT"
readme = "README.md"
description = "Easily hash and verify passwords using bcrypt"
homepage = "https://github.com/Keats/rust-bcrypt"
repository = "https://github.com/Keats/rust-bcrypt"
keywords = ["bcrypt", "password", "web", "hash"]
edition = "2018"

[dependencies]
blowfish = { version = "0.4", features = ["bcrypt"] }
rand = "0.7"
lazy_static = "1"
base64 = "0.11"
byteorder = "1"

[dev-dependencies]
quickcheck = "0.9.0"
