[package]
name = "bcrypt"
version = "0.1.7"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
readme = "README.md"
description = "Easily hash and verify passwords using bcrypt"
homepage = "https://github.com/Keats/rust-bcrypt"
repository = "https://github.com/Keats/rust-bcrypt"
keywords = ["bcrypt", "password", "web", "hash"]

[dependencies]
blowfish = { version = "0.3", features = ["bcrypt"] }
rand = "0.4"
lazy_static = "1"
base64 = "0.9"
byte-tools = "0.2"
